### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by BraedonM** [BraedonM/Assignmentor#3]
- [ ] https://github.com/BraedonM/assignmentor/issues/1
- [ ] https://github.com/BraedonM/assignmentor/issues/2
- [ ] Grade calculator functionality within each course, tab at top for grades
- [ ] Completed assignments tab
- [ ] Course & course color customization tab
